services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: voxlog
      POSTGRES_USER: voxlog
      POSTGRES_DB: voxlog
    ports:
      - '3254:5432'
    restart: always
    container_name: voxlog-postgres

  # web:
  #     build: .
  #     command: yarn start
